spring.application.name=user_service

spring.datasource.url=${USER_SERVICE_DB_URL:jdbc:postgresql://localhost:5434/user_service}
spring.datasource.username=${USER_SERVICE_DB_USERNAME:postgres}
spring.datasource.password=${USER_SERVICE_DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.issuer=${AUTH_JWT_ISSUER:auth_service}
app.security.jwt.secret=${AUTH_JWT_SECRET:change-this-secret-key-change-this-secret-key-change-this-secret-key}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.enabled=${APP_KAFKA_ENABLED:true}
app.kafka.topics.user-events=${APP_KAFKA_TOPIC_USER_EVENTS:user.events}
app.kafka.topics.directory-events=${APP_KAFKA_TOPIC_DIRECTORY_EVENTS:directory.events}
