spring.application.name=projects_service

spring.datasource.url=${PROJECTS_SERVICE_DB_URL:jdbc:postgresql://localhost:5436/projects_service}
spring.datasource.username=${PROJECTS_SERVICE_DB_USERNAME:postgres}
spring.datasource.password=${PROJECTS_SERVICE_DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.issuer=${AUTH_JWT_ISSUER:auth_service}
app.security.jwt.secret=${AUTH_JWT_SECRET:change-this-secret-key-change-this-secret-key-change-this-secret-key}
app.user-service.base-url=${USER_SERVICE_URL:http://user-service:8082}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.enabled=${APP_KAFKA_ENABLED:true}
app.kafka.topics.project-events=${APP_KAFKA_TOPIC_PROJECT_EVENTS:project.events}
